www:
  image: geographica/nginx4dev:js
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./public:/usr/share/nginx/html
    - .:/usr/share/nginx/html/src
    - ./nginx_dev/conf.d:/etc/nginx/conf.d


builder:
  build: .
  volumes:
    - .:/usr/src/app
